testProject/bbb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('taobao/', include('taobao.urls'))
]

testProject/taobao/urls.py
from django.urls import path
from . import views, Email
app_name = 'taobao'

urlpatterns = [
    #   首页
    path('', views.index, name='index'),

    #   用户管理
    path('user_control', views.user_control, name='user_control'),

    #   注册用户
    path('user_Registered/', views.user_Registered, name='user_Registered'),

    #   登录用户
    path('user_Login/', views.user_Login, name='user_Login'),

    #   退出登录
    path('logout/', views.logout, name='logout'),

    #   查看账户信息
    path('user_look/', views.user_look, name='user_look'),

    #   商城预览
    path('shopping/', views.shopping, name='shopping'),

    #   忘记密码
    path('verify/', views.verify, name='verify'),
    path('reset_password/', views.reset_password, name='reset_password'),

    #   查看用户登录记录
    path('user_history/', views.user_history, name='user_history'),

    #   修改密码
    path('modify_password/', views.modify_password, name='modify_password'),
    path('modify_modify_password_2/', views.modify_password_2, name='modify_password_2'),

    #   账号充值
    path('recharge/', views.recharge, name='recharge'),

















    #   购买商品
    path('<user_id>/buy/', views.buy, name='buy'),

    #   加入购物车
    path('<user_id>/<commodity_id>/add_cart/', views.add_cart, name='add_cart'),

    #   查看购物车
    path('<user_id>/look_cart/', views.look_cart, name='look_cart'),


    #   结算购物车
    path('<user_id>/buy_summarize/', views.buy_summarize, name='buy_summarize'),

    #   清空购物车
    path('<user_id>/buy_empty/', views.buy_empty, name='buy_empty'),





]


urlpatterns += [
    #   验证是否是商家
    path('permission/', views.permission, name='permission'),

    #   升级商家支付金额
    path('deduct/', views.deduct, name='deduct'),

    #   发布商品
    path('commodity_pub/', views.commodity_pub, name='commodity_pub'),

    #   查看发布的商品
    path('commodity_look_pub/', views.commodity_look_pub, name='commodity_look_pub'),

    #   向上翻页
    path('<page>/commodity_look_pub_up/', views.up, name='up'),

    #   向下翻页
    path('<page>/commodity_look_pub_next/', views.next, name='next'),


















    #   验证账号是否正确
    # path('commodity_login/', views.commodity_login, name='commodity_login'),

    #   验证是否是商家
    # path('commodity_user/', views.commodity_user, name='commodity_user'),



    #   查看商品的分类
    path('<user_id>/commodity_sort/', views.commodity_sort, name='commodity_sort'),

    #   添加商品分类
    path('<user_id>/add_sort/', views.add_sort, name='add_sort'),

    #   确认添加商品分类
    path('<user_id>/check_add_sort/', views.check_add_sort, name='check_add_sort'),




    #   添加商品
    # path('<user_id>/commodity_add/', views.commodity_add, name='commodity_add'),


    #   商品的大标题
    path('<user_id>/commodity_BigTitle/', views.commodity_BigTitle, name='commodity_BigTitle'),


    #   修改商品
    path('<user_id>/commodity_modify/', views.commodity_modify, name='commodity_modify'),

    #   发布修改后商品
    path('<commodity_id>/<user_id>/commodity_modify_sub/', views.commodity_modify_usb, name='commodity_modify_sub'),
    path('<commodity_id>/<user_id>/commodity_modify_2/', views.commodity_modify_2, name='commodity_modify_2'),

]
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('send/', Email.send, name='send')
]

testProject/taobao/models.py
from django.db import models
import os
from django.utils import timezone
import random

def user_upload_to(instance, filename):
    ext = os.path.splitext(filename)[1]
    fn = "%s_%s%s" % (timezone.now().strftime("%Y%m%d%H%M%S"),
                      random.randint(100000, 999999),
                      ext)
    return "portrait/%s" % fn


class Users(models.Model):
    user_account = models.CharField(max_length=20, blank=False)
    user_password = models.CharField(max_length=200, blank=False)
    user_question = models.CharField(max_length=50, default='', blank=False)
    user_answer = models.CharField(max_length=50, default='', blank=False)
    user_name = models.CharField(max_length=20, default='', blank=False)
    user_RMB = models.DecimalField(max_digits=10, decimal_places=2, default=0, blank=False)
    user_time = models.DateTimeField(auto_now_add=True, blank=False)
    user_state = models.CharField(max_length=20, default='0', blank=False)
    user_portrait = models.FileField(upload_to=user_upload_to, default='portrait/default.jpg')

    class Meta:
        db_table = 'User'


class User_login_history(models.Model):
    loginuser_id = models.ForeignKey(Users, on_delete=models.CASCADE)
    login_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'user_login_history'


class Commodity_sort(models.Model):
    sort_name = models.CharField(max_length=200, blank=False)
    sort_shortcut = models.CharField(max_length=200, blank=False)

    class Meta:
        db_table = 'commodity_sort'




def commodity_upload_to(instance, filename):
    ext = os.path.splitext(filename)[1]
    fn = "%s_%s%s" % (timezone.now().strftime("%Y%m%d%H%M%S"),
                      random.randint(100000, 999999),
                      ext)
    return "photos/%s" % fn


class Commodity(models.Model):
    commodity_id = models.CharField(max_length=200, primary_key=True, blank=False)
    commodity_name = models.CharField(max_length=200, blank=False)
    commodity_price = models.DecimalField(max_digits=10, decimal_places=2, blank=False)
    commodity_sort = models.CharField(max_length=200, blank=False)
    stock = models.IntegerField(default=0, blank=False)
    commodity_photo = models.FileField(upload_to=commodity_upload_to, blank=False)

    publish_date = models.DateTimeField(default=timezone.now())
    modify_date = models.DateTimeField(auto_now=True, blank=False)
    commodity_user = models.ForeignKey(Users, on_delete=models.CASCADE, blank=False)

    class Meta:
        db_table = 'Commodity'


# class Commodity_modify_log(models.Model):
#     commodity_id = models.ForeignKey(Commodity, on_delete=models.CASCADE)
#     modify_time = models.DateField(auto_now_add=True)
#     modify_detail = models.CharField(max_length=200)
#
#     class Meta:
#         db_table = 'Commodity_modify_log'


class Shopping_cart(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    commodity_id = models.CharField(max_length=200, primary_key=True)
    commodity_name = models.CharField(max_length=200)
    commodity_price = models.DecimalField(max_digits=10, decimal_places=2)
    commodity_num = models.IntegerField()
    commodity_sum = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = 'Shopping_cart'

testProject/taobao/views.py
from django.shortcuts import render
from .models import *
from .forms import *
from django.utils import timezone
from django.db.models import F

from django.http import response, HttpResponse, HttpResponseRedirect

import time
import math
import random
import hashlib
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate
from django.contrib.auth.models import User as auth_user
from django.contrib.auth.decorators import login_required


def index2(request):
    return render(request, 'taobao/index2.html')

#   首页
def index(request):
    return render(request, 'taobao/index.html')


#   用户管理
def user_control(request):
    return render(request, 'taobao/user_control.html')


#   注册用户
def user_Registered(request):
    form = LoginForm()
    if request.method == "POST":
        form = LoginForm(request.POST, request.FILES)
        print(request.FILES)
        # is_valid()方法用于验证提交的数据是否符合Form类的字段定义
        if form.is_valid():
            if Users.objects.filter(user_account=form.cleaned_data['user_account']).exists():
                error_msg = "账号重复，请重新输入"
                context = dict()
                context['form'] = form
                context['error_msg'] = error_msg
                return render(request, 'taobao/user_Registered.html', context)

            result = form.save()
            if result:
                a = Users.objects.get(user_account=form.cleaned_data['user_account'])
                request.session['user_id'] = a.id
                User_login_history.objects.create(loginuser_id=a, login_time=timezone.now())
                return render(request, 'taobao/index.html')
    context = dict()
    context['form'] = form
    return render(request, 'taobao/user_Registered.html', context)


#   登录用户
# def user_Login(request):
#     if request.session.get('user_id'):
#         error = '你已经登录用户'
#         context = dict()
#         context['errors'] = error
#         return render(request, 'taobao/user_login.html', context)
#     form = LoginUser()
#     if request.method == 'POST':
#         form = LoginUser(request.POST)
#
#         if form.is_valid():
#             if User.objects.filter(user_account=form.cleaned_data['user_account']).exists():
#                 a = User.objects.get(user_account=form.cleaned_data['user_account'])
#                 user_password = make_password(form.cleaned_data['user_password'])
#                 if a.user_password == user_password:
#                     User_login_history.objects.create(loginuser_id=a, login_time=timezone.now())
#                     request.session['user_id'] = a.id
#                     return render(request, 'taobao/index.html')
#             error = '账号或密码错误'
#             context = dict()
#             context['form'] = form
#             context['errors'] = error
#             return render(request, 'taobao/user_login.html', context)
#
#
#     context = dict()
#     context['form'] = form
#     return render(request, 'taobao/user_login.html', context)
#

#   登录用户
def user_Login(request):
    if request.session.get('user_id'):
        error = '你已经登录用户'
        context = dict()
        context['errors'] = error
        return render(request, 'taobao/user_login.html', context)
    form = LoginUser()
    if request.method == 'POST':
        form = LoginUser(request.POST)
        if form.is_valid():
            if Users.objects.filter(user_account=form.cleaned_data['user_account']).exists():
                a = Users.objects.get(user_account=form.cleaned_data['user_account'])
                if a.user_password == form.cleaned_data['user_password']:
                    User_login_history.objects.create(loginuser_id=a, login_time=timezone.now())
                    request.session['user_id'] = a.id
                    return render(request, 'taobao/index.html')
            error = '账号或密码错误'
            context = dict()
            context['form'] = form
            context['errors'] = error
            return render(request, 'taobao/user_login.html', context)
    context = dict()
    context['form'] = form
    return render(request, 'taobao/user_login.html', context)


#   查看用户登录记录
def user_history(request):
    user_history = User_login_history.objects.all()
    print(user_history)
    return render(request, 'taobao/user_history.html', {'user_history': user_history})


#   查看用户账号信息
def user_look(request):
    user_id = request.session.get('user_id', '游客')
    if user_id == '游客':
        return render(request, 'taobao/user_look.html', {'user_id': user_id})
    user = Users.objects.get(pk=user_id)
    a = str(user.user_portrait)
    return render(request, 'taobao/user_look.html', {'user_id': user.user_account, 'user_user': user, 'a': a})


#   退出登录
def logout(request):
    user_id = request.session.get('user_id')
    if user_id:
        request.session.pop("user_id")
    return render(request, 'taobao/index.html')


#   购物商城
def shopping(request):
    return render(request, 'taobao/shopping.html')


#   充值账户余额
def recharge(request):
    user_id = request.session.get('user_id', '游客')
    context = dict()
    form = Recharge()
    if user_id == '游客':
        context['error'] = '你暂时没有登录，请登录'
        context['form'] = form
        return render(request, 'taobao/recharge.html', context)
    if request.method == 'POST':
        form = Recharge(request.POST)
        if form.is_valid():
                Users.objects.filter(pk=user_id).update(user_RMB=form.cleaned_data['user_RMB'] + F('user_RMB'))
                return render(request, 'taobao/index.html')
    context['a'] = '不是游客'
    context['form'] = form
    context['user_id'] = user_id
    return render(request, 'taobao/recharge.html', context)


#   忘记密码的验证账号
def verify(request):
    form = VerifyUser()
    url = 'verify.html'
    if request.method == 'POST':

        form = VerifyUser(request.POST)

        if form.is_valid():
            if Users.objects.filter(user_account=form.cleaned_data['user_account']).exists():
                user = Users.objects.get(user_account=form.cleaned_data['user_account'])
                request.session['user_id'] = user.id
                return render(request, 'taobao/reset_password.html', {'user': user})
            else:
                error = '账号不存在'
            context = dict()
            context['error'] = error
            context['form'] = form
            return render(request, 'taobao/' + url, context)

    context = dict()
    context['form'] = form
    return render(request, 'taobao/' + url, context)


#   忘记密码的修改密码
def reset_password(request):
    a = request.session.get('user_id')
    b = Users.objects.get(pk=a)
    if b.user_answer == request.POST['user_answer']:
        Users.objects.filter(pk=a).update(user_password=request.POST['user_password'])
        return render(request, 'taobao/index.html')
    else:
        c = '密码问题错误'
        return render(request, 'taobao/reset_password.html', {'user': b, 'question_error': c})


#   修改账户密码
def modify_password(request):
    a = request.session.get('user_id')
    return render(request, 'taobao/modify_password.html', {'user_id': a})


#   修改账户密码
def modify_password_2(request):
    a = request.session.get('user_id')
    Users.objects.filter(pk=a).update(user_password=request.POST['user_password'])
    return render(request, 'taobao/index.html')


#   验证商家权限
def permission(request):
    a = request.session.get('user_id', None)
    if a is None:
        error = '你暂时没有登录，请登录'
        content = dict()
        content['error'] = error
        return render(request, 'commodity/permission.html', content)
    b = Users.objects.get(pk=a)
    if b.user_state == '0':
        a = '不是商家'
        content = dict()
        content['a'] = a
        return render(request, 'commodity/permission.html', content)
    if b.user_state == '1':
        return render(request, 'commodity/index.html')


#   扣除100000金额成为商家
def deduct(request):
    a = Users.objects.get(pk=request.session.get('user_id'))
    if int(a.user_RMB) < 100000:
        b = '金额不足,请进行充值'
        return render(request, 'commodity/permission.html', {'b': b})
    else:
        Users.objects.filter(pk=a.id).update(user_RMB=F('user_RMB') - 100000, user_state='1')
        return render(request, 'commodity/index.html')


#   发布商品
def commodity_pub(request):
    form = CommodityForm()
    content = dict()
    if request.method == 'POST':
        form = CommodityForm(request.POST, request.FILES)
        if form.is_valid():
            a = math.ceil(time.time())
            b = form.cleaned_data['commodity_sort'] + str(a) + str(random.randint(1, 10)) * 6
            form.instance.commodity_id = b
            form.instance.commodity_user = Users.objects.get(pk=request.session.get('user_id'))
            form.save()
            return render(request, 'commodity/index.html')
    content['form'] = form
    return render(request, 'commodity/pub_commodity.html', content)


#   查看发布的商品
def commodity_look_pub(request):
    a = Users.objects.get(pk=request.session.get('user_id'))
    page = 1
    b = Commodity.objects.filter(commodity_user=a)[(int(page) - 1) * 2:int(page) * 2]
    return render(request, 'commodity/commodity_look_pub.html', {'commodity': b, 'page': page})





#   向上翻页
def up(request, page):
    a = Users.objects.get(pk=request.session.get('user_id'))
    b = Commodity.objects.filter(commodity_user=a)[(int(page)-1) * 2:(int(page)) * 2]
    return render(request, 'commodity/commodity_look_pub.html', {'commodity': b, 'page': page})


# 向下翻页
def next(request, page):
    a = Users.objects.get(pk=request.session.get('user_id'))
    b = Commodity.objects.filter(commodity_user=a)[(int(page)) * 2:(int(page)+1) * 2]
    return render(request, 'commodity/commodity_look_pub.html', {'commodity': b, 'page': page})


























#   购买商品
def buy(request, user_id):
    commoditys = Commodity.objects.all()
    return render(request, 'taobao/buy.html', {'user_id': user_id, 'commoditys': commoditys})


#   加入购物车

testProject/taobao/templates/commodity/add_sort.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加商品分类</title>
</head>
<body>
<form action="{%url 'taobao:check_add_sort' user_id%}" method="post">
    {%csrf_token%}
    请输入添加的商品分类的名字：<input type="text" name="sort_name">
    请输入添加的商品分类的简称：<input type="text" name="sort_shortcut" placeholder="三位大写字母">
    <input type="submit" name="确认添加">
    <input type="button" value="返回上一级" onclick="location.href= '{%url 'taobao:commodity_BigTitle' user_id %}'">
</form>
</body>
</html>

testProject/taobao/templates/commodity/commodity_BigTitle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商家标题</title>
</head>
<body>

    <a href="{%url 'taobao:commodity_pub' user_id %}">发布商品</a>
    <a href="{%url 'taobao:commodity_look_pub' user_id %}">查看发布的商品</a>
    <a href="{%url 'taobao:commodity_modify' user_id %}">修改发布的商品</a>
    <a href="{%url 'taobao:commodity_sort' user_id%}">查看商品的分类</a>
    <br>
    <a href="{%url 'taobao:Enter'%}"><input type="button" value="返回首页"></a>

</body>
</html>

testProject/taobao/templates/commodity/commodity_init.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商户升级</title>
</head>
<body>
    <div>
        {{b}}
    </div>

    你现在还不是商家，升级为商家需要交付10w元保证金，是否支付？
    <a href="{%url 'taobao:decuct' user_id%}">支付</a>
    <br>

    <a href="{%url 'taobao:Enter'%}"><input type="button" value="返回首页"></a>
</body>
</html>

testProject/taobao/templates/commodity/commodity_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        {%if password_error%}
            <h1>你输入的密码错误</h1>
        {%endif%}
        {%if account_error%}
            <h1>你输入的账号错误</h1>
        {%endif%}
    <form action="{%url 'taobao:commodity_user'%}" method="post">
        {%csrf_token%}
        请输入账号：<input type="text" name="user_account">
        请输入密码：<input type="text" name="user_password">
        <input type="submit" value="登录">
    </form>
</body>
</html>

testProject/taobao/templates/commodity/commodity_look_pub.html
{%extends 'taobao/index.html'%}
{%load static%}
{% load strs %}
{%block content%}

        <ul id="ul">
            {% for i in commodity %}
            <li>

            商品编号：{{i.commodity_id}}
            商品名字：{{i.commodity_name}}
            商品价格：{{i.commodity_price}}
            商品分类：{{i.commodity_sort}}
            商品库存：{{i.stock}}
            商品发布日期：{{i.publish_date|date:'Y-m-d H-i-s'}}

            商品图片:<img src="{% replace_str i.commodity_photo %}" style="width: 100px; height: 100px;">
            </li>


        {%empty%}
                你暂时没有发布任何商品
        {% endfor %}

        </ul>


        <br>
        <a href="{%url 'taobao:up' page%}" id="prev">上一页</a>
        <a href="{%url 'taobao:next' page%}" id="next">下一页</a>




<script type="text/javascript" src="{% static 'taobao/js/jquery.js'%}"></script>
<script>
	$(document).ready(function(){
		$("#next").click(function(){
			console.log('2222222222')
			htmlobj=$.ajax({url:"{% url 'taobao:up' page%}",async:false});
			$("#ul").html(htmlobj.responseText);
			
		})
	})
	
</script>
{%endblock%}

testProject/taobao/templates/commodity/commodity_look_pub2.html
{% for i in commodity %}
    <li>
    商品编号：{{i.commodity_id}}
    商品名字：{{i.commodity_name}}
    商品价格：{{i.commodity_price}}
    商品分类：{{i.commodity_sort}}
    商品库存：{{i.stock}}
    商品发布日期：{{i.publish_date|date:'Y-m-d H-i-s'}}

    商品图片:<img src="{% replace_str i.commodity_photo %}" style="width: 100px; height: 100px;">
    </li>

{%empty%}
        你暂时没有发布任何商品
{% endfor %}

testProject/taobao/templates/commodity/commodity_modity.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改商品</title>
</head>
<body>

    {%if user%}

    <h1>请选中你要修改的商品：</h1>
    {%for i in user.commodity_set.all%}
    <a href="{%url 'taobao:commodity_modify_sub' i.commodity_id user_id %}">
        商品编号：{{i.commodity_id}}
        商品名字：{{i.commodity_name}}
        商品价格：{{i.commodity_price}}
        商品分类：{{i.commodity_sort}}
        商品库存：{{i.stock}}
        商品发布日期：{{i.publish_date}}
    </a>
    {%empty%}
        你暂时没有发布任何商品
    {%endfor%}

    {%endif%}
    <br>
<input type="button" value="返回上一级" onclick="location.href= '{%url 'taobao:commodity_BigTitle' user_id %}'">

</body>
</html>

testProject/taobao/templates/commodity/commodity_modity_sub.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>发布修改后的商品</title>
</head>
<body>

    {%if commodity_id%}
        {%if commodity%}
        <h2>你正在修改的商品编号为：{{commodity_id}}</h2>
        <form action="{%url 'taobao:commodity_modify_2' commodity_id user_id %}" method="post">
            {% csrf_token %}
        请修改以下信息：
        商品名字：<input type="text" name="commodity_name">
        商品价格：<input type="text" name="commodity_price">
        商品库存：<input type="text" name="stock">
            <input type="submit" value="提交">
        </form>
        {%endif%}
    {%endif%}
</body>
</html>

testProject/taobao/templates/commodity/commodity_sort.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商品分类</title>
</head>
<body>
    <ul>
    {%for i in commodity_sort%}
        <li>
            商品的名称是：{{i.sort_name}}
            商品的编号是：{{i.sort_shortcut}}
        </li>
        {%empty%}
            现在没有商品的分类
    {%endfor%}

    </ul>

<input type="button" value="添加商品分类" onClick="location.href= '{%url 'taobao:add_sort' user_id%}'">
<input type="button" value="返回上一级" onclick="location.href= '{%url 'taobao:commodity_BigTitle' user_id %}'">
</body>
</html>

testProject/taobao/templates/commodity/index.html
{%extends 'taobao/index.html'%}

{%block content%}
    <center>

        <h1><a href="{%url 'taobao:commodity_pub'%}">发布商品</a></h1>
        <h1><a href="{%url 'taobao:commodity_look_pub'%}">查看发布的商品</a></h1>
        {%comment%}
        <h1><a href="{%url 'taobao:commodity_modify'%}">修改发布的商品</a></h1>
        <h1><a href="{%url 'taobao:commodity_sort'%}">查看商品的分类</a></h1>
        {%endcomment%}
    </center>
{%endblock%}

testProject/taobao/templates/commodity/permission.html
{%extends 'taobao/index.html'%}

{%block content%}
  <center>
        {%if error%}
            <h1>{{error}}</h1>
        {%endif%}

        {%if b%}
            <h1>{{b}}</h1>
        {%endif%}

        {% if a%}
            <h1>你现在还不是商家，升级为商家需要交付10w元保证金，是否支付？</h1>
            <input type="button" value="支付" onclick="location.href= '{%url 'taobao:deduct'%}'">
        {%endif%}

  </center>
{%endblock%}

testProject/taobao/templates/commodity/pub_commodity.html
{%extends 'taobao/index.html'%}
{%block content%}
<center>
    <form action="{% url 'taobao:commodity_pub'%}" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        <ul>
            <h1>{{form.as_ul}}</h1>
        </ul>
        {{form.error}}
        <br>
        <input type="submit" value="发布">
    </form>
</center>



{%comment%}
   <form action="{%url 'taobao:commodity_add' user_id%}" method="post">
        {%csrf_token%}
        商品名称：<input type="text" name="commodity_name"> <br>
        商品单价：<input type="text" name="commodity_price"> <br>
        商品分类：


        <select name="commodity_sort">
            {%for i in commodity_sort%}
           <option value="i.sort_shortcut">{{i.sort_shortcut}}</option>
           {%endfor%}
        </select> <br>

        库存数量：<input type="text" name="stock"> <br>
        <input type="submit" value="发布">
    </form>
{%endcomment%}


{%endblock%}